### ISSUE TITLE
Struggling with output

### ISSUE THREAD

**Issue by cmcguff** [paulspringett/csv_shaper#21]
I'm sure I've got this set up correct, but is not returning an actual CSV file for download - what am I missing? I can inspect the csv_string and it has the values I expect in there, just the render csv command seems to be doing nothing?

      csv_string = CsvShaper.encode do |csv|
        csv.headers :user_id, :total_leave_requested
        csv.rows @results do |csv, result|
          csv.cell :user_id, result.user_id
          csv.cell :total_leave_requested, result.total_leave_requested
        end
      end   
      render csv: csv_string

**Comment by smnplk** [comment]
This is an old question: 

Instead of render, try: 

    send_data(csv_string, filename: 'leaves.csv')

**Comment by paulspringett** [comment]
Hey @cmcguff sorry for not replying to this. Did you get it working in the end?
